import appName from './appName.js';

const namespace = `${appName}/area`;

export default {
  GET_AREA_ASSETS_REQUEST: `${namespace}/GET_AREA_ASSETS_REQUEST`,
  GET_AREA_ASSETS_SUCCESS: `${namespace}/GET_AREA_ASSETS_SUCCESS`,
  GET_AREA_ASSETS_FAIL: `${namespace}/GET_AREA_ASSETS_FAIL`,
  SAVE_SETTINGS_REQUEST: `${namespace}/SAVE_SETTINGS_REQUEST`,
  SAVE_SETTINGS_SUCCESS: `${namespace}/SAVE_SETTINGS_SUCCESS`,
  SAVE_SETTINGS_FAIL: `${namespace}/SAVE_SETTINGS_FAIL`,
  GET_AREA_RESOURCES_REQUEST: `${namespace}/GET_AREA_RESOURCES_REQUEST`,
  GET_AREA_RESOURCES_SUCCESS: `${namespace}/GET_AREA_RESOURCES_SUCCESS`,
  GET_AREA_RESOURCES_FAIL: `${namespace}/GET_AREA_RESOURCES_FAIL`,
  GET_ROUTE_RESOURCES_REQUEST: `${namespace}/GET_ROUTE_RESOURCES_REQUEST`,
  GET_ROUTE_RESOURCES_SUCCESS: `${namespace}/GET_ROUTE_RESOURCES_SUCCESS`,
  GET_ROUTE_RESOURCES_FAIL: `${namespace}/GET_ROUTE_RESOURCES_FAIL`
};
